### ISSUE TITLE
React to FS changes

### ISSUE THREAD

**Issue by foxcpp** [Hexawolf/SSProto#1]
Indexed files can change from time to time. Isn't it boring to always restart server? Use https://github.com/fsnotify/fsnotify/.

**Comment by Hexawolf** [comment]
It was enough to create just [WIP] PR if you make a suggestion but this is fine.

**Comment by foxcpp** [comment]
inotify is a bit too complex for our case, I think I found a better (simplier) solution. And that's why I renamed this issue because I'm not going to use inotify for it.
